// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: normalize.proto

package normalize

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NormalizeService_NormalizeTable_FullMethodName = "/normalize.NormalizeService/NormalizeTable"
)

// NormalizeServiceClient is the client API for NormalizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NormalizeServiceClient interface {
	NormalizeTable(ctx context.Context, in *TableData, opts ...grpc.CallOption) (*NormalizedTable, error)
}

type normalizeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNormalizeServiceClient(cc grpc.ClientConnInterface) NormalizeServiceClient {
	return &normalizeServiceClient{cc}
}

func (c *normalizeServiceClient) NormalizeTable(ctx context.Context, in *TableData, opts ...grpc.CallOption) (*NormalizedTable, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NormalizedTable)
	err := c.cc.Invoke(ctx, NormalizeService_NormalizeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NormalizeServiceServer is the server API for NormalizeService service.
// All implementations must embed UnimplementedNormalizeServiceServer
// for forward compatibility.
type NormalizeServiceServer interface {
	NormalizeTable(context.Context, *TableData) (*NormalizedTable, error)
	mustEmbedUnimplementedNormalizeServiceServer()
}

// UnimplementedNormalizeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNormalizeServiceServer struct{}

func (UnimplementedNormalizeServiceServer) NormalizeTable(context.Context, *TableData) (*NormalizedTable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NormalizeTable not implemented")
}
func (UnimplementedNormalizeServiceServer) mustEmbedUnimplementedNormalizeServiceServer() {}
func (UnimplementedNormalizeServiceServer) testEmbeddedByValue()                          {}

// UnsafeNormalizeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NormalizeServiceServer will
// result in compilation errors.
type UnsafeNormalizeServiceServer interface {
	mustEmbedUnimplementedNormalizeServiceServer()
}

func RegisterNormalizeServiceServer(s grpc.ServiceRegistrar, srv NormalizeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNormalizeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NormalizeService_ServiceDesc, srv)
}

func _NormalizeService_NormalizeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalizeServiceServer).NormalizeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalizeService_NormalizeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalizeServiceServer).NormalizeTable(ctx, req.(*TableData))
	}
	return interceptor(ctx, in, info, handler)
}

// NormalizeService_ServiceDesc is the grpc.ServiceDesc for NormalizeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NormalizeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "normalize.NormalizeService",
	HandlerType: (*NormalizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NormalizeTable",
			Handler:    _NormalizeService_NormalizeTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "normalize.proto",
}
